### ISSUE TITLE
jupyter 安装 TOC 插件失败

### ISSUE THREAD

**Issue by sujuxiaoren** [neolee/wop-community#13]
老师，您好。
我这里遇到 jupyter 安装 TOC 插件失败的问题
用命令行安装
![aaa](https://user-images.githubusercontent.com/48588846/85944432-46473d80-b969-11ea-8571-e3b376e2ec84.png)

当开这个log以后，是这样显示的：
Node v14.4.0

Yarn configuration loaded.
> C:\Users\微软中国\scoop\apps\nodejs\current\npm.CMD pack @jupyterlab/toc
Error: EPERM: operation not permitted, mkdir 'C:\Users\微锟斤拷锟叫癸拷\scoop'
Error: EPERM: operation not permitted, mkdir 'C:\Users\微锟斤拷锟叫癸拷\scoop'

Traceback (most recent call last):

  File "c:\users\微软中国\scoop\apps\python\current\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "c:\users\微软中国\scoop\apps\python\current\lib\site-packages\jupyterlab\labextensions.py", line 93, in start
    ans = self.run_task()

  File "c:\users\微软中国\scoop\apps\python\current\lib\site-packages\jupyterlab\labextensions.py", line 149, in run_task
    for i, arg in enumerate(self.extra_args)

  File "c:\users\微软中国\scoop\apps\python\current\lib\site-packages\jupyterlab\labextensions.py", line 149, in <listcomp>
    for i, arg in enumerate(self.extra_args)

  File "c:\users\微软中国\scoop\apps\python\current\lib\site-packages\jupyterlab\commands.py", line 388, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "c:\users\微软中国\scoop\apps\python\current\lib\site-packages\jupyterlab\commands.py", line 603, in install_extension
    info = self._install_extension(extension, tempdir, pin=pin)

  File "c:\users\微软中国\scoop\apps\python\current\lib\site-packages\jupyterlab\commands.py", line 1499, in _install_extension
    info = self._extract_package(extension, tempdir, pin=pin)

  File "c:\users\微软中国\scoop\apps\python\current\lib\site-packages\jupyterlab\commands.py", line 1580, in _extract_package
    path = glob.glob(pjoin(tempdir, '*.tgz'))[0]

IndexError: list index out of range

Exiting application: jupyter

如果直接在浏览器点击安装，则会出现以下错误提示：
![ScreenShot_20200628180322](https://user-images.githubusercontent.com/48588846/85944523-f9179b80-b969-11ea-9810-df01b0d7c61c.png)
![ScreenShot_20200628180424](https://user-images.githubusercontent.com/48588846/85944532-03d23080-b96a-11ea-8761-e9c51fc99dd6.png)

**Comment by neolee** [comment]
我怀疑和你的中文用户名有关。这个插件不是必须的，甚至也不怎么重要，先放着吧。

**Comment by tyler1zhang** [comment]
从这一段提示信息看，系统的中文编码有点问题。 

```
Error: EPERM: operation not permitted, mkdir 'C:\Users\微锟斤拷锟叫癸拷\scoop'
```

为了避免这个问题，最简单的方法是把系统默认语言改为英文。其次是只改你的登陆电脑的用户名为英文名。这是个逼自己学英文的好机会。

**Comment by sujuxiaoren** [comment]
> 从这一段提示信息看，系统的中文编码有点问题。
> 
> ```
> Error: EPERM: operation not permitted, mkdir 'C:\Users\微锟斤拷锟叫癸拷\scoop'
> ```
> 
> 为了避免这个问题，最简单的方法是把系统默认语言改为英文。其次是只改你的登陆电脑的用户名为英文名。这是个逼自己学英文的好机会。

我为了解决这个问题，执拗地把系统重装了🤣

**Comment by tyler1zhang** [comment]
> > 从这一段提示信息看，系统的中文编码有点问题。
> > ```
> > Error: EPERM: operation not permitted, mkdir 'C:\Users\微锟斤拷锟叫癸拷\scoop'
> > ```
> > 
> > 
> > 为了避免这个问题，最简单的方法是把系统默认语言改为英文。其次是只改你的登陆电脑的用户名为英文名。这是个逼自己学英文的好机会。
> 
> 我为了解决这个问题，执拗地把系统重装了rofl

可以看看[这个视频](https://www.bilibili.com/video/av79265783/?p=3)的11:40s开始那一段。里面讲了windows系统的中文解码的历史遗留问题。
