### ISSUE TITLE
在 Greeting 类中添加 is_good() 方法运行失败

### ISSUE THREAD

**Issue by Liujiale02** [neolee/wop-community#185]
```
class GreetingBot(Bot):
    
    def _q(self):
        return "How are you today?"

    def is_good(feeling):
        g = feeling.lower()
        if ('good' in g or 'fine' in g) and g.find('not') == -1:
            return True
        elif 'bad' in g or 'not' in g:
            return False
        return False

    def _think(self, s):
        if is_good(s):
            return "I'm feeling good too."
        else:
            return "Sorry to hear that."
```
运行结果：
```
Traceback (most recent call last):
  File "garfield.py", line 146, in <module>
    garfield.run()
  File "garfield.py", line 134, in run
    bot.run()
  File "garfield.py", line 41, in run
    self._run_once()
  File "garfield.py", line 29, in _run_once
    self._say(self._think(a))
  File "garfield.py", line 69, in _think
    if is_good(s):
NameError: name 'is_good' is not defined
```

这种函数(is_good)该怎么用才行？

**Comment by neolee** [comment]
如果你要这样使用的话，`is_good()` 函数要在类定义的外面定义；如果你在类定义里面定义的话，这个函数就要用类似于 `self.is_good()` 这样的名字来调用，而且其输入参数里要加上 `self`。

**Comment by Liujiale02** [comment]
```
class Bot:

...

def _is_good(self, s):
        self.s = s.lower()

        if ('good' in s or 'fine' in s ) and s.find('not') == -1:
            return True
        elif 'bad' in s or 'not' in s:
            return False
        return False

...

class GreetingBot(Bot):
    
    def _q(self):
        return "How are you today?"

    def _think(self, s):
        if self._is_good(s):
            return "I'm feeling good too."
        else:
            return "Sorry to hear that."
```

我在基类Bot里添加了一个方法 `def _is_good( )`，能运行成功。

我这种方式是不是老师说的--**这个定义是类定义的外面定义**？

那么另外一种在类定义里面定义，是不是要在`Greeting(Bot)`里面的？我一直调试不出来。

**Comment by neolee** [comment]
两种方法。

一种是把这个函数定义放在类定义的外面，一个普普通通的函数，就当普普通通的函数（类似 `pint()` 那样）使用就好了。

另一种是作为类里面对象方法，那么就像 `_think()` `_say()` 这种，放在类定义里面，第一个参数必须是 `self`，调用时用 `self._is_good()` 这样的语法。

你现在用的是后一种方法，但是为啥要放 `Bot` 基类里呢？这个明明只有 `GreetingBot` 类对象会用到，这个函数定义就放在 `GreetingBot` 类里面就好了啊。

前一种方法你可以参考我分享的这个版本： https://github.com/neolee/garfield/blob/master/bots/greeting_bot.py

**Comment by Liujiale02** [comment]
OK，基本上已经理解清楚了。

**Comment by Amy20191** [comment]
```
    def _is_good(self, feeling):
        g = feeling.lower()
        if('good' in g or 'fine' in g) and g.find('not') == -1:
            return True
        elif 'bad' in g and 'not' in g:
            return True
        else:
            return False
```

```
    def _is_good(self, feeling):
        self.feeling = feeling
        g = self.feeling.lower()
        if('good' in g or 'fine' in g) and g.find('not') == -1:
            return True
        elif 'bad' in g and 'not' in g:
            return True
        else:
            return False
```

老师，这两段代码，哪段是对的呢？都可以运行的。作为在类里面的对象方法，什么情况下需要写 `self.feeling = feeling` 类似这样的语句？

**Comment by neolee** [comment]
@Amy20191 你的表述不是很清楚，我猜你是想问什么时候使用属性 `self.xxx` 什么时候使用普通的局部变量 `xxx`。

这个判断其实挺简单的，如果你希望一个变量在对象的不同方法中都能使用，其值是所有方法共享的，就将其实现为对象的属性（`self.xxx`）；反之，如果你只在一个方法里用到的变量，就作为普通的局部变量好了。
