### ISSUE TITLE
brew services start mysql 显示错误

### ISSUE THREAD

**Issue by Liujiale02** [neolee/wop-community#276]
macOS系统安装mysql
```
在命令行界面运行下面的命令即可：
brew install mysql@5.7
brew services start mysql@5.7
```

第一句运行成功了，当我输入第二行`brew services start mysql@5.7`就出现以下错误：

```
liujiale@LiujialedeMacBook-Pro ~ % brew services start mysql@5.7
Error: undefined method `named' for #<OptionParser:0x00007fbfc732c178>
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:67:in `run!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:48:in `services'
/usr/local/Homebrew/Library/Homebrew/brew.rb:111:in `<main>'
```

**Comment by neolee** [comment]
比较奇怪的错误，看看下面这个有没有帮助：

https://github.com/Homebrew/legacy-homebrew/issues/37809

**Comment by Liujiale02** [comment]
终于运行成功了！感谢老师的帮助。

我简单地讲解一下吧，方便后来可能也会遇上同样问题的同学。
```
当在命令行界面运行下面的安装mysql命令：
brew install mysql@5.7
brew services start mysql@5.7
```
如果当输入并运行第二句`brew services start mysql@5.7`出现错误时，可以通过更新Homebrew来解决问题。
在命令行界面运行代码：`brew update && brew upgrade`，然后坐等运行完毕。
